### ISSUE TITLE
Consolidate Recurring Payment and Managed Recurring Into One Page

### ISSUE THREAD

**Issue by ACSCORP** [ACSCORP/ALCOLOCK-myprogram-website#16]
![screen shot 2016-01-13 at 3 32 10 pm](https://cloud.githubusercontent.com/assets/16691301/12307025/ddd296e4-ba0a-11e5-8c4b-5e1786487521.jpg)

**Comment by kr1st1n4gr03g3r** [comment]
notes: 8.   Consolidate “Managed Recurrings” and “Recurring Payment” into “Manage Billing” or similar where the user can setup the recurrent payment and once setup he will have the summary per program of when the next payment will be (date), how many payments are left and the payment amount being deducted.
The user will have the option to cancel the payments and setup a new one under the same tab, rather than having two separate tabs. The “recurring payment” tab is disabled once the recurrent payment has been set.
• Size font for the day in #2 needs to match the font of the fields in #1
• Recurrent payment amount needs to be darker and not show as a button

**Comment by kr1st1n4gr03g3r** [comment]
![image](https://cloud.githubusercontent.com/assets/7462118/12459972/671198f0-bf7f-11e5-9a6e-e6ecbbe0c795.png)
